### ISSUE TITLE
Market data wrapper keeps disconnecting

### ISSUE THREAD

**Issue by rehmatuc** [mtusman/gemini-python#1]
Hi, 
I'm trying to use the MarketDataWS class to connect to Gemini's market data websocket. However, after a minute or so afterwards of initialising the class it keeps disconnecting and repeatedly showing the error message "socket is already closed" and doesn't record any trades.

This is my following code:
```python
from gemini import MarketDataWS
a = MarketDataWS('btcusd')
a.start()
```

and after a minute or so the following message keeps repeating forever:

```python
...
socket is already closed 
socket is already closed
socket is already closed
socket is already closed
socket is already closed
socket is already closed
```

Also when i try to force close the connection it just freezes and when I press CTRL + C , I get the following error:
```python
>>> a.close()
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/code/gemini/basewebsocket.py", line 54, in close
    self.thread.join()
  File "/usr/local/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/local/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
>>> Connection is already closed.

--Ended Connection--
```

**Comment by mtusman** [comment]
Hey, 

Thanks for reporting the issue. I was able to replicate this error. However, upon further investigation, the problem seems to be not on the code itself, but the fact that the Gemini website is currently experience problems with their services as reported on their status page (https://status.gemini.com/). However, their services should be back to operational in a few hours/days and you should no longer be experiencing this problem. I'm going to keep the issue open for a few days, just in case Gemini get their services up and the problem seems to persist. Otherwise, I'll close it.
